import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
	ADROUTER_CATALOG_PATH,
	computeAdRouterCatalogDigest,
	parseAdRouterCatalog,
	validateAdRouterCatalog,
} from "../packages/ai/scripts/adrouter-catalog.ts";

const catalog = parseAdRouterCatalog(readFileSync(ADROUTER_CATALOG_PATH));

function expectInvalid(mutator, pattern = /invalid_adrouter_catalog/) {
	const candidate = structuredClone(catalog);
	mutator(candidate);
	assert.throws(() => validateAdRouterCatalog(candidate), pattern);
}

function expectInvalidWithValidDigest(mutator, pattern = /invalid_adrouter_catalog/) {
	expectInvalid((candidate) => {
		mutator(candidate);
		candidate.catalog_digest = computeAdRouterCatalogDigest({
			schema_version: candidate.schema_version,
			models: candidate.models,
		});
	}, pattern);
}

test("accepts the committed Router catalog", () => {
	assert.deepEqual(
		catalog.models.map(({ id, context_window, max_input_tokens, max_output_tokens }) => ({
			id,
			context_window,
			max_input_tokens,
			max_output_tokens,
		})),
		[
			{ id: "deepseek-v4-flash", context_window: 1_048_576, max_input_tokens: 917_504, max_output_tokens: 65_536 },
			{ id: "deepseek-v4-pro", context_window: 1_048_576, max_input_tokens: 851_968, max_output_tokens: 131_072 },
			{ id: "mimo-v2.5", context_window: 1_048_576, max_input_tokens: 917_504, max_output_tokens: 65_536 },
			{ id: "mimo-v2.5-pro", context_window: 1_048_576, max_input_tokens: 851_968, max_output_tokens: 131_072 },
			{ id: "agnes-2.0-flash", context_window: 524_288, max_input_tokens: 458_752, max_output_tokens: 65_536 },
			{ id: "agnes-2.5-flash", context_window: 524_288, max_input_tokens: 458_752, max_output_tokens: 65_536 },
			{ id: "agnes-2.5-pro", context_window: 1_048_576, max_input_tokens: 851_968, max_output_tokens: 131_072 },
			{ id: "agnes-2.5-pro-alpha", context_window: 1_048_576, max_input_tokens: 786_432, max_output_tokens: 196_608 },
		],
	);
});

test("rejects schema, digest, and key drift", () => {
	expectInvalid((candidate) => {
		candidate.schema_version = 2;
	});
	expectInvalid((candidate) => {
		candidate.catalog_digest = `sha256:${"0".repeat(64)}`;
	});
	expectInvalid((candidate) => {
		candidate.extra = true;
	});
	expectInvalid((candidate) => {
		candidate.models[0].configured = true;
	});
});

test("rejects model order, identity, class, and thinking drift even with a valid digest", () => {
	for (const mutate of [
		(candidate) => candidate.models.reverse(),
		(candidate) => (candidate.models[0].id = candidate.models[1].id),
		(candidate) => (candidate.models[0].provider = "qwen"),
		(candidate) => (candidate.models[0].model_class = "frontier"),
		(candidate) => (candidate.models[0].thinking_levels = ["none", "high"]),
		(candidate) => (candidate.models[0].default_thinking_level = "high"),
	]) {
		expectInvalidWithValidDigest(mutate);
	}
});

test("rejects missing, duplicate, swapped, copied, malformed, and impossible tuples", () => {
	for (const mutate of [
		(candidate) => candidate.models.pop(),
		(candidate) => (candidate.models[1] = structuredClone(candidate.models[0])),
		(candidate) => {
			const first = candidate.models[0];
			const second = candidate.models[1];
			[first.max_input_tokens, second.max_input_tokens] = [second.max_input_tokens, first.max_input_tokens];
			[first.max_output_tokens, second.max_output_tokens] = [second.max_output_tokens, first.max_output_tokens];
		},
		(candidate) => {
			candidate.models[4].context_window = candidate.models[0].context_window;
			candidate.models[4].max_input_tokens = candidate.models[0].max_input_tokens;
			candidate.models[4].max_output_tokens = candidate.models[0].max_output_tokens;
		},
		(candidate) => (candidate.models[0].context_window += 1),
		(candidate) => (candidate.models[0].max_input_tokens += 1),
		(candidate) => (candidate.models[0].max_output_tokens += 1),
		(candidate) => (candidate.models[0].max_output_tokens = 65_536.5),
		(candidate) => (candidate.models[0].max_input_tokens = 0),
		(candidate) => (candidate.models[0].max_output_tokens = -1),
		(candidate) => {
			candidate.models[0].context_window = 10;
			candidate.models[0].max_input_tokens = 8;
			candidate.models[0].max_output_tokens = 8;
		},
	]) {
		expectInvalidWithValidDigest(mutate);
	}
});

test("invalid synchronization input leaves vendored and generated bytes unchanged", () => {
	const directory = mkdtempSync(join(tmpdir(), "adrouter-invalid-catalog-"));
	const source = join(directory, "invalid.json");
	const generatedPath = "packages/ai/src/providers/adrouter.models.ts";
	const vendorBefore = readFileSync(ADROUTER_CATALOG_PATH);
	const generatedBefore = readFileSync(generatedPath);
	try {
		const invalid = structuredClone(catalog);
		invalid.models[0].max_output_tokens = -1;
		invalid.catalog_digest = computeAdRouterCatalogDigest({
			schema_version: invalid.schema_version,
			models: invalid.models,
		});
		writeFileSync(source, JSON.stringify(invalid));
		const result = spawnSync(process.execPath, ["scripts/sync-adrouter-catalog.mjs", "--source", source], {
			encoding: "utf8",
		});
		assert.notEqual(result.status, 0);
		assert.deepEqual(readFileSync(ADROUTER_CATALOG_PATH), vendorBefore);
		assert.deepEqual(readFileSync(generatedPath), generatedBefore);
	} finally {
		rmSync(directory, { recursive: true, force: true });
	}
});
