// Generated from upstreams.lock.json by scripts/generate-upstream-metadata.mjs.
// Do not edit this file by hand.

export const GENERATED_BUNDLED_EXTENSION_CONTRACTS = [
	{
		name: "pi-subagents",
		commands: [
			"chain",
			"parallel",
			"run",
			"run-chain",
			"subagents-doctor",
			"subagents-interrupt",
			"subagents-resume",
			"subagents-status",
			"subagents-stop",
		],
		tools: ["subagent"],
		handlers: ["session_start", "session_shutdown", "tool_result"],
		relativePath: ["pi-subagents-0.68.0", "src", "extension", "index.ts"],
	},
	{
		name: "pi-cache-optimizer",
		commands: ["cache", "cache-optimizer"],
		handlers: ["before_agent_start", "message_end", "session_shutdown", "session_start"],
		relativePath: ["pi-cache-optimizer-2.8.10", "index.ts"],
	},
	{
		name: "btw",
		commands: ["btw"],
		relativePath: ["btw-23017e9", "index.ts"],
	},
	{
		name: "pi-web-access",
		commands: ["curator", "google-account", "search", "websearch"],
		tools: ["fetch_content", "get_search_content", "web_search"],
		handlers: ["session_shutdown", "session_start", "session_tree"],
		shortcuts: ["ctrl+shift+w"],
		relativePath: ["pi-web-access-0.29.0", "dist", "index.js"],
	},
] as const;

export const GENERATED_BUNDLED_SKILL_DIRECTORIES = [
	["pi-subagents-0.68.0", "skills"],
	["pi-web-access-0.29.0", "skills"],
	["adroutercli", "skills"],
] as const;

export const GENERATED_REQUIRED_BUNDLED_SKILLS = ["adroutercli", "librarian", "pi-subagents"] as const;

export const GENERATED_BUNDLE_DIRECTORIES = [
	"adroutercli",
	"btw-23017e9",
	"pi-cache-optimizer-2.8.10",
	"pi-subagents-0.68.0",
	"pi-web-access-0.29.0",
] as const;
